[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.8.0"
authors = [
    "Alex Morega <alex@grep.ro>",
    "Johannes Drönner <droenner@informatik.uni-marburg.de>"
    ]
repository = "https://github.com/georust/gdal"
edition = "2018"

[features]
default = []
bindgen = ["gdal-sys/bindgen"]
array = ["ndarray"]
datetime = ["chrono"]

[dependencies]
thiserror = "1.0"
libc = "0.2"
geo-types = { version = "0.7" }
gdal-sys = { path = "gdal-sys", version = "^0.4"}
ndarray = {version = "0.15", optional = true }
chrono = { version = "0.4", optional = true }
bitflags = "1.2"

[build-dependencies]
gdal-sys = { path = "gdal-sys", version= "^0.4"}
semver = "1.0"

[dev-dependencies]
tempfile = "3.2"
trybuild = "1.0.42"

[workspace]
members = ["gdal-sys"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
